package com.Andreea.LibraryManagementSystem.util;

public enum Genre {
    LITERARY_FICTION,
    NON_FICTION,
    MYSTERY_SUSPENSE,
    SCIENCE_FICTION,
    FANTASY,
    ROMANCE,
    HISTORICAL_FICTION,
    PSYCHOLOGICAL_THRILLER,
    HORROR,
    YOUNG_ADULT,
    CHILDREN_BOOKS,
    POETRY,
    DRAMA,
    SELF_HELP,
    TRAVEL_BOOKS,
    ADVENTURE,
    CURRENT_AFFAIRS_NEWS,
    FASHION_BEAUTY,
    TECHNOLOGY_GADGETS,
    TRAVEL_ADVENTURE,
    HEALTH_FITNESS,
    ART_CULTURE,
    CUISINE_GASTRONOMY,
    SCIENCE_DISCOVERIES,
    FINANCE_BUSINESS

}

